/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* USER CODE BEGIN Includes */
#include "assembler.h"
/* USER CODE END Includes */

int main(void)
{
  /* USER CODE BEGIN 1 */
  ASM_main();
  ASM_loop();
  /* USER CODE END 1 */
}
